[advisories]
informational_warnings = ["unmaintained", "unsound"]

[database]
fetch = true
stale = false

[output]
deny = ["unsound", "yanked"]
format = "terminal"
quiet = false
show_tree = true

[yanked]
enabled = true
update_index = true
